name             'solr'
maintainer       'Leandro Di Tommaso'
maintainer_email 'leandro.ditommaso@mikroways.net'
license          'MIT'
description      'Installs the solr search engine.'
long_description 'See README.md'
version          '0.5.0'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'

depends 'apt'
depends 'java'
